### PR TITLE
Fix card spacing 

### LINKED ISSUE #69: Laptop for families card is wider than the rest
I am not sure why this is but I know if you remove the divider daisyUI class from the card the sizes all become uniform. Any other ideas to fix the problem would be great too.

### PR DESCRIPTION
**Pull request by RedFox0x20**
Card the cards were using the `md:space-x-4` class, this class has some strange
behaviour for calculating the grid gaps however it did not interact with the
first element correctly.

The cards are now slightly more cramped however the strange size discrepancy no longer exists.

This should fix #69

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export default function Home() {
             <div className="md:flex md:justify-center">
               <MainDonationForm />
             </div>
-            <div className="md:grid md:grid-cols-3 md:gap-5 md:space-x-4 ">
+            <div className="md:grid md:grid-cols-3 md:gap-5 ">
```
Comment (marekrozmus) [inline pages/index.js:91]: try

```javascript
<div className="md:grid md:grid-cols-3 md:gap-x-8 md:gap-y-5">
```

spacing should look like it was before

Comment (RedFox0x20) [reply pages/index.js:91]: Yes that does the trick, thanks!

**Comment by audreyfeldroy** [comment]
Nice job figuring this out, and great teamwork @RedFox0x20 @marekrozmus. Thanks for this!
