### PR TITLE
Fixed the footer floating issue now it sticks to bottom irrespective …

### LINKED ISSUE #208: Sitewide Height Layout Standard
### Footer And Content Relationship

The site can use some work on the `PrimaryLayout` component to produce predictable behavior in the way content relates to the footer. Currently, on higher resolutions, the `Footer` floats below where the content stops. It should be done with `Tailwind` utility classes. This [question](https://stackoverflow.com/questions/47925751/how-to-fill-the-height-of-the-viewport-with-tailwind-css) might help guide you.

We're looking for each page to have:

- [ ] Footer sticky at the bottom at higher resolutions.
- [ ] Footer pushed out of view at lower resolutions when the content fills the screen (  css equivalent  -`overflow: scroll` ).

### PR DESCRIPTION
**Pull request by Sahil-101**
Now the footer sticks at the bottom at higher resolution, pushed out in lower resolution.
Closes #208

### CODE REVIEW

**Review by ozer619 — APPROVED** [review]
Looks good to me @Sahil-101 .

File: components/PrimaryLayout.js [hunk 1]
```diff
@@ -8,13 +8,13 @@ import Navbar from './Navbar';
 
 export default function PrimaryLayout({ children }) {
   return (
-    <>
+    <div className="flex flex-col min-h-screen">
```
Comment (LowLifeArcade) [inline components/PrimaryLayout.js:11]: Awesome @Sahil-101! This works like a charm 🔮  The only thing I'd say is it might be better if this div with the Tailwind classes here be moved to line 15 just above the `NavBar`. Ideally the head info should be outside of the layout elements. You'll need to re-add the <> </> for this to work though as React needs fragments for multiple elements.

**Review by LowLifeArcade — CHANGES_REQUESTED** [review]

File: components/PrimaryLayout.js (hunk 1 above)
Comment (Sahil-101) [reply components/PrimaryLayout.js:11]: Oh would change it, I understood Thanks for pointing out :sweat_smile:

Comment (LowLifeArcade) [reply components/PrimaryLayout.js]: @Sahil-101 this is perfect!

**Review by LowLifeArcade — APPROVED** [review]
